# Generated by Django 4.2.2 on 2023-07-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('episode_url', models.URLField()),
                ('thumbnail', models.ImageField(upload_to='')),
                ('postcast_name', models.CharField(max_length=255)),
                ('guide', models.CharField(max_length=55)),
            ],
        ),
    ]
